# Generated by Django 5.1.6 on 2025-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_address2'),
        ('products', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_favorites',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
