# Generated by Django 5.1.6 on 2025-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='ahmedreda199785@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=123456, max_length=50),
        ),
    ]
