# Generated by Django 5.1.6 on 2025-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='person',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
