# Generated by Django 5.1.6 on 2025-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price'], 'verbose_name': 'products NAME'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Tanta', 'Tanta')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='put your text', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photos/2023/1230/package-1.jpg', upload_to='photos/%y/%m%d', verbose_name='photo'),
        ),
    ]
